### ISSUE TITLE
Page not loading after Barba js transition

### ISSUE THREAD

**Issue by david1opez** [david1opez/Mentes-Brillantes#5]
on **index.html : 234**
```html
      <ul class="transition">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>

on **index.html : 47**
```html
    <style>
        ul.transition {
            display: flex;
            position: fixed;
            z-index: 999999;
            height: 100vh;
            width: 120%;
            top: 0;
            left: -100px;
            margin: 0;
            pointer-events: none;
            list-style: none;
        }

        ul.transition li {
            transform: scaleY(0);
            background: #FFC940;
            width: 20%;
        }
    </style>
```

on **index.html : 253**
```html
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js"></script>
    <script src="https://unpkg.com/@barba/core"></script>
```

on **index.html : 287**
```css
        barba.init({
            transitions: [{
                async leave(data) {
                    const done = this.async();
                    pageTransition();
        
                    await delay(1500);
                },
                async enter(data) {}
            }]
        });
```

on **transition.js**
```javascript
function pageTransition() {
    var tl = gsap.timeline();

    tl.to("ul.transition li", {
        duration: .5,
        scaleY: 1,
        transformOrigin: "bottom left",
        stagger: .2
    });

    tl.to("ul.transition li", {
        duration: .5,
        scaleY: 0,
        transformOrigin: "bottom left",
        stagger: .1,
        delay: .1
    })
}

function delay(n) {
    n = n || 2000;

    return new Promise(done => {
        setTimeout(() => {
            done();
        }, n)
    })
}
```

**Comment by hasnaindev** [comment]
Hello,

Can you make sure that the page you are trying to go to has barba _wrapper_ and _container_ in the proper places? I had this issue when I was moving from a proper barba page to another page IE from client side pages to admin side pages where the barba attributes weren't implemented.

Barba fails to load the new page, it says on the same page and loses its contents too. I tried to replicate this issue successfully by removing barba tags from blog page which resulted in new page load failure and barba stayed on the same pages. I simply prevented barba on all my admin side pages using the _prevent_ attribute.

You can find more about _prevent_ attribute on the [barba's strategies](https://barba.js.org/docs/advanced/strategies/#prevent) page. Please, let me know if you have resolved this or have another explanation or solution.

Thanks.

**Comment by david1opez** [comment]
> Hello,
> 
> Can you make sure that the page you are trying to go to has barba _wrapper_ and _container_ in the proper places? I had this issue when I was moving from a proper barba page to another page IE from client side pages to admin side pages where the barba attributes weren't implemented.
> 
> Barba fails to load the new page, it says on the same page and loses its contents too. I tried to replicate this issue successfully by removing barba tags from blog page which resulted in new page load failure and barba stayed on the same pages. I simply prevented barba on all my admin side pages using the _prevent_ attribute.
> 
> You can find more about _prevent_ attribute on the [barba's strategies](https://barba.js.org/docs/advanced/strategies/#prevent) page. Please, let me know if you have resolved this or have another explanation or solution.
> 
> Thanks.

Thank you so much for your help bro.
After breaking my head for several days i've figured out whats wrong 🙃

**Comment by david1opez** [comment]
**FIXED :**

on **index.html : 287**
```javascript
        barba.init({
            sync: true,
            transitions: [{
                async leave(data) {
                    const done = this.async();
                    pageTransition();
                    await delay(1500);
                    done(); //It just added this
                },
                async enter(data) {}
            }]
        });
```
